# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "masterTemp" ]
  pull_request:
    branches: [ "masterTemp" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./dockertemp
    #runs-on: ${{ matrix.os }}
    #strategy:
      #matrix:
        #os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Build with Maven
        run: mvn -B package --file TempMaven/pom.xml
        
      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: shrutipalekar/demo-repository
          registry: docker.io
          #tag: demo-image
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          working-directory: ${{ env.working-directory}}
          dockerfile: dockertemp/Dockerfile

  #publish:
    #needs: build
    #runs-on: ubuntu-latest
    #steps:
      #- name: Publish artifacts
        #run: echo "Publishing artifacts"
